# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Python\_Project\copied\ui\Forms\MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(MainForm)
        self.pushButton.setGeometry(QtCore.QRect(50, 70, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "copied"))
        self.pushButton.setText(_translate("MainForm", "PushButton"))
